# trigger:
# - main

# pool:
#   vmImage: 'windows-latest'

# steps:
# - task: NodeTool@0
#   inputs:
#     versionSpec: '14.x'
#   displayName: 'Install Node.js'

# - script: |
#     cd UdemyCypress
#     npm install cypress
#   displayName: 'Install Cypress Locally'

# - script: |
#     cd UdemyCypress
#     npm install
#   displayName: 'npm install'

# - script: |
#     cd UdemyCypress
#     npx cypress run --record --key 97a65ad6-2d3c-4d5d-8794-45d5976bd1b8 --spec cypress/e2e/examples/eaapp.spec.cy.js
#   displayName: 'Run Cypress Tests'
trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- script: |
    for /f %%i in ('dir /b /ad /s $(Build.SourcesDirectory)\*') do (
      if exist "%%i\$(cypressDirectory)\package.json" (
        echo "Cypress project found in %%i"
        cd "%%i\$(cypressDirectory)"
        set cypressPath=%%i\$(cypressDirectory)
        exit /b 0
      )
    )
    echo "Error: Cypress project not found"
    exit /b 1
  displayName: 'Find and navigate to Cypress Directory'

- script: |
    cd $(cypressPath)
    npm install cypress
  displayName: 'Install Cypress Locally'

- script: |
    cd $(cypressPath)
    npm install
  displayName: 'npm install'

- script: |
    cd $(cypressPath)
    npx cypress run --record --key 97a65ad6-2d3c-4d5d-8794-45d5976bd1b8 --spec cypress/e2e/examples/eaapp.spec.cy.js
  displayName: 'Run Cypress Tests'
