# trigger:
# - main

# pool:
#   vmImage: 'windows-latest'

# steps:
# - task: NodeTool@0
#   inputs:
#     versionSpec: '14.x'
#   displayName: 'Install Node.js'

# - script: |
#     cd UdemyCypress
#     npm install cypress
#   displayName: 'Install Cypress Locally'

# - script: |
#     cd UdemyCypress
#     npm install
#   displayName: 'npm install'

# - script: |
#     cd UdemyCypress
#     npx cypress run --record --key 97a65ad6-2d3c-4d5d-8794-45d5976bd1b8 --spec cypress/e2e/examples/eaapp.spec.cy.js
#   displayName: 'Run Cypress Tests'

# trigger:
# - main

# pool:
#   vmImage: 'windows-latest'

# variables:
#   cypressPath: 'UdemyCypress'

# steps:
# - task: NodeTool@0
#   inputs:
#     versionSpec: '14.x'
#   displayName: 'Install Node.js'

# - script: |
#     echo "cypressPath is set to: $(cypressPath)"
#     cd $(cypressPath)
#     npm install cypress
#   displayName: 'Install Cypress Locally'

# - script: |
#     cd $(cypressPath)
#     npm install
#   displayName: 'npm install'

# - script: |
#     cd $(cypressPath)
#     npx cypress run --record --key 97a65ad6-2d3c-4d5d-8794-45d5976bd1b8 --spec cypress/e2e/examples/eaapp.spec.cy.js
#   displayName: 'Run Cypress Tests'

trigger:
- main

pool: 'TestingPool'

variables:
  cypressPath: ''

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    for /d %%i in (*) do (
        if exist "%%i\cypress" (
            echo "Cypress found in directory: %%i"
            echo "##vso[task.setvariable variable=cypressPath]%%i"
            exit /b
        )
    )
  displayName: 'Find Cypress Directory'

- script: |
    echo "cypressPath is set to: $(cypressPath)"
    cd $(cypressPath)
    npm install cypress
  displayName: 'Install Cypress Locally'

- script: |
    cd $(cypressPath)
    npm install
  displayName: 'npm install'

- script: |
    cd $(cypressPath)
    npx cypress run --record --key 97a65ad6-2d3c-4d5d-8794-45d5976bd1b8 --spec cypress/e2e/examples/eaapp.spec.cy.js
  displayName: 'Run Cypress Tests'

