trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    cd UdemyCypress
    npm install cypress
  displayName: 'Install Cypress Locally'

- script: |
    cd UdemyCypress
    npm install
  displayName: 'npm install'

- script: |
    cd UdemyCypress
    npx cypress run --record --key 97a65ad6-2d3c-4d5d-8794-45d5976bd1b8 --spec cypress/e2e/examples/eaapp.spec.cy.js
  displayName: 'Run Cypress Tests'
